# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
rojo = "rojo-rbx/rojo@7.5.1"
run-in-roblox = "rojo-rbx/run-in-roblox@0.3.0"
wally = "upliftGames/wally@0.3.2"
darklua = "seaofvoices/darklua@0.16.0"
selene = "Kampfkarren/selene@0.28.0"
stylua = "JohnnyMorganz/stylua@2.1.0"
